/* 
	Sanjeev Singh

	stockTrade.cpp

	Calculates the gain/losses generated by a 
	stock invetment after buying and selling shares 
	on the stock market through iTrade online broker 
	platform
*/


// Header files
#include <iostream>
#include <string>
using namespace std;

int main()
{
	//variables
	float numberOfShares, costPerShareAtBuying, pricePerShareAtSelling, totalCost, totalProceeds, commissionPaid, gains_losses, commissionAtBuying, commissionAtSelling, totalCommission;
	float commission, percent;
	string companyName, companySymbol;

	commission = 0.02;

	//TItle and inputs
	cout << "Stock Invetment Performance Calculator ..." << endl;
	cout << "" << endl;
	cout << "Company Name (no spaces) & Symbol:     ";
	cin >> companyName >> companySymbol;
	cout << "Number of Shares transacted:           ";
	cin >> numberOfShares;
	cout << "Cost per Share (@ buying):             ";
	cin >> costPerShareAtBuying;
	cout << "Price per Share (@ selling):           ";
	cin >> pricePerShareAtSelling;

	// Displays Report title
	cout << "" << endl;
	cout << "Realized Gains/Losses Report ..." << endl;
	cout << "-----------------------------------------" << endl;
	
	// Displays stock name and Quantity of stocks
	cout << "Stock:          " << companyName << " (" << companySymbol << ")" << endl;
	cout << "Quantity:       " << numberOfShares << " shares." << endl;
	cout << "" << endl;
	
	
	// Math to find total cos , total proceeds, total commisions , gains/losses and percent for gains/losses
	commissionAtBuying = (numberOfShares * costPerShareAtBuying * commission);
	commissionAtSelling = (numberOfShares * pricePerShareAtSelling * commission);
	totalCost = (costPerShareAtBuying * numberOfShares) + (commissionAtBuying);
	totalProceeds = (numberOfShares * pricePerShareAtSelling) - (commissionAtSelling);
	totalCommission = commissionAtSelling + commissionAtBuying;
	gains_losses = totalProceeds - totalCost;
	percent = (gains_losses / totalCost) * 100;


	// Displays total cost, total proceeds, commission and gains/losses
	cout << "Total Cost:     " << "$" << totalCost << endl;
	cout << "Total Proceeds: " << "$" << totalProceeds << endl;
	cout << "Commissions:    " << "$" << totalCommission << endl;
	cout << "Gains/Losses:   " << "$" << gains_losses << " " << "(" << percent << "%)" << endl;

	return 0;
	 
}